신청 API 구현
Step3-kakao-tech-campus/Team3_BE pull request #17
Opened 2023-09-27 13:43 UTC by xcelxlorx

## Summary
신청 API를 구현했습니다. 
- 신청자 목록 조회
- 모집글에 대한 신청
- 신청 수락
- 신청 취소 또는 거절

## Description

### 신청자 목록 조회
- 신청자 목록은 20개씩 applicant.id 내림차순 기준으로 가져오도록 설정했습니다. 커서 size가 없으면 디폴트 값 20을 넣어줬습니다. 커서 key가 있으면 키보다 작은 데이터를 보내고, 키가 없으면 가장 마지막 id부터 가져옵니다.
- 연관 엔티티 user, post가 검색 조건에는 필요하지만 실제 데이터는 사용되지 않으므로 join fetch가 아닌 join을 사용했습니다.
- 평점 기능이 구현되지 않아 rating은 모두 1.0으로 전달됩니다. 

### 모집글에 대한 신청
- user.id, post.id에 대한 유니크 조건을 추가했지만 신청 중복 확인 로직도 추가했습니다. 

### 테스트
```
INSERT INTO post_tb (title) VALUES ('제목');
```
```
@Entity
@Getter
@DynamicInsert
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Table(name = "post_tb")
public class Post {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(length = 100)
    private String title;
}

```

위의 코드처럼 적당히 post에 넣고 유니크 조건이랑 신청 중복 부분 주석 처리하면 한 사용자마다 post 요청 여러 번 할 수 있어서 페이징 결과 확인하실 수 있습니다! 
## Related Issue

Issue Number: close #13

2023-09-27 23:52 UTC, jagaldol requested changes
리뷰 확인부탁드립니다!

2023-09-27 23:52 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
> +    int getApplicantNumber(@Param("postId") Long postId);
Long countByPostId로 바꿔주세요 JPA 형식에 맞는 메서드명입니다.

2023-09-27 23:52 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/applicant/repository/ApplicantRepository.java
> +    void updateStatus(@Param("applicantId") Long applicantId, @Param("status") Boolean status);
jpa에서 별도로 update문을 사용하지 않고 save를 통해 저장하거든요.

아니면 `@Transactional`인 서비스 함수인 경우에 select한 객체를 수정하면 자동으로 더티체킹돼서 update 쿼리 날아갑니다

2023-09-27 23:52 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
> +        public static GetApplicantsDto mapToGetApplicantsDto(Integer applicantNumber, List<Applicant> applicants){
이거 같은 경우에는 메서드명을 of로 해서 딴거와 통일 가능할까요?

2023-09-27 23:52 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
> +        applicantRepository.findByUserIdAndPostId(1L, postId).ifPresent(applicant -> {
userId가 1L로 하드 코딩 되어 있습니다.

2023-09-27 23:52 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
> +    public void create(User user, Long postId){
User를 바로 전달 받는데 JwtAuthenticationFilter를 보시면 인증 과정에서 id와 role만으로 User 객체를 만들어서 CustomUserDetails에 집어넣습니다. 매번 자신의 정보를 select 해오는게 비용이 커서 이렇게 해놨고요.

그런만큼 customUserDetails에서 꺼낸 User를 바로 쓰기 보단 userId만 추출해서 사용해서 서비스에서 User select가 필요하면 uiserId 기반으로 select query 날려서 들고와야합니다.

2023-09-27 23:52 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
> +        //게시글 작성자 신청 금지
이건 모집글 entity가 완성이 안되있어서 구현 안 하신 거 같은데 잘 보이게 `TODO:` 로 해주실 수 있나요

2023-09-27 23:52 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/applicant/dto/ApplicantResponse.java
> +                    1.0 //UserRate 생성된 후 수정
여기도 주석에 TODO: 해주세요

2023-09-27 23:52 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/applicant/service/ApplicantService.java
> +        applicantRepository.updateStatus(applicant.getId(), requestDto.status());
repository에서 언급했다시피 updatequery 날리기 보단

applicant.updateStatus(requestDto.status()); 만 하셔도 될거에요.

Applicant 엔티티에 updateStatus라는 setter하나 만들어서 변경해주세요

2023-09-28 00:53 UTC, sososo0 reviewed
repository로 post나 applicant를 찾는 과정의 코드가 함수에서 중복되는 부분이 있는데요,
이 부분을 따로 함수로 빼는 것이 코드 중복도 줄이고, 추후에 유지보수에도 좋을 것 같네요!

2023-09-28 01:22 UTC, xcelxlorx commented
수정했습니다 확인 부탁드립니다!

2023-09-28 01:37 UTC, jagaldol approved these changes
수고하셨습니다!

2023-09-28 01:53 UTC, merged