모집글 목록 조회 및 모집글 CRUD 기능 구현
Step3-kakao-tech-campus/Team3_BE pull request #19
Opened 2023-09-28 04:02 UTC by sososo0

## Summary
모집글 관련 기능 구현했습니다. 
- 모집글 목록 조회
- 모집글 상세 조회
- 모집글 생성
- 모집글 수정
- 모집글 삭제 

총 5가지 API를 구현하였습니다. 

## Description
### Post
- Post Entity 작성 시 아직 구현되지 않은 Comment, Score은 코드만 작성하고 주석 처리 하였습니다.
- 지역 관련 데이터가 아직 완성된 것 같지 않아, 지역 이름을 가져오는 함수는 임의로 "부산광역시 금정구 장전2동"를 반환하도록 하였습니다. 

### 모집글 목록 조회 
- 모집글 목록 조회에서 지역 id들과 전체 조회의 여부에 따라 가져오도록 하였습니다.
  - 마찬가지로 아직 지역 관련 데이터가 완성된 것 같지 않아, 지역 관련 설정은 테스트 해보지 않았습니다. 
  - 전체 조회의 여부에 따라서는 조회 기능이 작동해서 직접 테스트 해볼 수 있습니다. 

### Service Code 
- 서비스 코드 작성 시 함수를 public과 private으로 분리하였습니다. 분리한 이유는 실제 동작하고 적용이 되게하는 로직은 밖으로 노출될 필요가 없다고 생각해서 분리시켰습니다. 
  - public은 겉으로 보기에 이해할 수 있을 정도로만 작성하였습니다. 
  - private에는 실제 작동하는 로직이 구현되어있습니다. 

## Related Issue

Issue Number: #12

2023-09-28 08:30 UTC, jagaldol requested changes
지금 모집글 목록 조회 GET /posts 의 로직이 잘못되어 있습니다. 그외에도 수정사항이 너무 많아서 일단 요청사항들 수정 다 해주시고 추가적으로 잘못된 거 없는지 한번 더 자체 검토 후 재 리뷰 요청 보내주시길 바랍니다.

지역 선택같은 경우 데이터 파싱해서 가져온 4500개 가량의 데이터가 아직 머지 안됐을 뿐, 직접 입력한 15개 정도의 데이터로 충분히 잘 동작하고 있습니다. service와 repository까지 전부 다 만들어 두었으니 districtRepository 사용하여서 작업하시면 됩니다.

2023-09-28 08:30 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/controller/PostController.java
> +            @RequestBody @Valid PostRequest.UpdatePostDto request
여기도 Errors errors 넣어주시길 바랍니다.

2023-09-28 08:30 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/controller/PostController.java
> +        postService.update(userDetails.user(), postId, request.toEntity(userDetails.user()));
마찬가지로 Dto에서 Entity로 Entity에서 Dto로의 변환은 전부 service 로직 내부에서 하도록 userId와 request, postId만 service 코드로 넘기도록 변경 부탁드립니다.

컨트롤러에서는 요청에 대한 검증 및 응답만을 담당합니다.

그리고 userDetails.user()도 하지 마시고 getId()로 userId만 추출 해서 사용부탁드립니다.

2023-09-28 08:30 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/controller/PostController.java
> +                .location(URI.create("/api/posts/" + postId))
status OK인데 location을 줄 필요가 있나요? created의 경우 생성된 데이터의 주소를 전달하는 용도로 필요하지만 update를 한 경우는 자기 자신의 주소로 클라이언트가 이미 가지고 있는 주소이므로 줄 필요가 없어 보입니다.

다른 파일들이랑 양식 맞추셔서 ResponseEntity.ok().body(ApiUtils.success());로 변경 부탁드립니다.

success의 경우 기본으로 200 OK로 설정되있기에 200은 따로 상태코드 전달 필요가 없습니다.

2023-09-28 08:30 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/controller/PostController.java
> +        return ResponseEntity.ok(ApiUtils.success(HttpStatus.OK));
여기도 userDetails.getId() 사용하게 변경해주시고

success()로 변경해주세요.

2023-09-28 08:30 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/dto/PostRequest.java
> +            @NotBlank(message = "모집글 내용은 필수 입력 사항입니다.")
위에는 NotEmpty 밑에는 NotBlank로 되어 있는데 NotEmpty로 양식 통일 부탁드립니다.

2023-09-28 08:30 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/repository/PostRepository.java
> +    List<Post> findAllById(@Param("id") Integer id);
이것도 어차피 Post가 country가 아니라 distrcit 가지고 있어야하긴한데 그거랑 별개로 JPA namedquery 규칙에 의하면 findAllByCountryId로 해야합니다.

2023-09-28 09:26 UTC, sososo0 commented on src/main/java/com/bungaebowling/server/post/Post.java
> +        return Optional.ofNullable(this.user.getImgUrl()).orElse(null);
의미가 없는 Optional 구문이라는 것은 알지만, 그럼에도 Optional을 사용한 이유는 NullPointerException을 방지하기 위해 사용하였습니다.

2023-09-28 09:34 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/Post.java
> +        return Optional.ofNullable(this.user.getImgUrl()).orElse(null);
함수내에서 imgrl을 optional로 변경하고 null이면 null로 다시 바꿔서 리턴하는데 따로 체크 되는게 없지않나요? 

nullpointerexception 체크하려면 차라리 this.user.imgUrl말고 this.user에 대해 optional로 체크 한다음에 imgurl에 접근하는게 맞지않나요

2023-09-28 09:46 UTC, sososo0 commented on src/main/java/com/bungaebowling/server/post/Post.java
> +        return Optional.ofNullable(this.user.getImgUrl()).orElse(null);
음.. 사용자가 프로필 이미지를 설정할 수도 있고 안할 수도 있을 것이라고 생각을 해서 imgUrl에 대해서만 null 체크를 하였습니다.  
 this.user에 대해 optional로 체크 한다음에 imgurl에 접근하는 것이라면 this.user에 대해서 null인 상황을 체크하는 것이라고 생각이 드는데,,, 제가 이해한 것이 맞나요?

2023-09-28 09:52 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/Post.java
> +        this.startTime = post.getDueTime();
네 그 상황 외에는 null 체크 필요없어 보여서요. 지금 코드가 프로필 이미지가 null인지 체크한다음에 null이면 null을 리턴하는 식으로 되있어요

그대로 프로필 이미지 같은 경우 null 값을 그대로 준다음 null에 대한 동작 방식은 서비스쪽에서 처리하는게 맞아보이거든요

2023-09-28 09:55 UTC, sososo0 commented on src/main/java/com/bungaebowling/server/post/Post.java
> +        this.startTime = post.getDueTime();
아하 넵 이해했습니다. 수정하겠습니다

2023-09-28 10:31 UTC, sososo0 commented on src/main/java/com/bungaebowling/server/post/Post.java
> +    public void update(Post post) { // 게시글 업데이트할 때 쓸 것
this. ~~를 사용해서 새로운 Post를 생성하는 것이 아닌, 기존의 Post 내용을 업데이트 한다고 생각하는데, 혹시 새로운 Post 객체를 만든다는 것에 대해서 설명해주실 수 있나요?

2023-09-28 10:50 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/Post.java
> +    public void update(Post post) { // 게시글 업데이트할 때 쓸 것
보면 put 요청에서 request가지고 새로운 Post 객체 newPost를 만든다음 newPost를 사용해서 원래 post에 업데이트를 하고 있거든요.

이렇게 새로운 Post객체를 만들지말고 바로 request에 있는값들로 update 해달라는 뜻입니다.
postId로 기존 Post 가져와서 내부 값들만 변경하면되는데 새로운 Post 객체를 만들어 버리니까, 불필요한 객체 생성으로 인해 낭비되는 비용도 있고 의미적으로도 새로운 포스트 생성하는게 아닌데 Post 객체를 만들어버려서 이상해요

2023-09-28 10:53 UTC, sososo0 commented on src/main/java/com/bungaebowling/server/post/Post.java
> +    public void update(Post post) { // 게시글 업데이트할 때 쓸 것
아하 넵, 수정하겠습니다

2023-09-28 16:13 UTC, sososo0 commented
comments들 반영해서 코드 수정하고 pr 다시 보냈습니다!

2023-09-29 03:18 UTC, jagaldol requested changes
getPosts 쪽에 페이징이 덜 구현되어 있습니다.

2023-09-29 03:18 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/repository/PostRepository.java
> +    List<Post> findAllWithCloseFalse();
여기위로 7개들도 각각 2개씩으로 분리 시키고 page 추가해줘야합니다.

2023-09-29 03:18 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/service/PostService.java
> +                return all ? postRepository.findAllByCityId(cityId) : postRepository.findAllByCityIdWithCloseFalse(cityId);
이 윗부분 코드들 수정이 pageable 받는 작업이 안돼있어요

2023-09-29 03:18 UTC, jagaldol commented on src/main/java/com/bungaebowling/server/post/service/PostService.java
> +        if (!post.isMine(userId)) {
이 권한 체크가  findById(postId);를 진행한 바로 다음줄에 있으면 좋을 거같아요.

권한 체크 먼저 하고 request에서 정보 들고오는게 좋아보입니다.

2023-09-29 08:34 UTC, jagaldol approved these changes
추가적인 수정 필요사항 일단 제가 직접 수정해서 올렸습니다.

2023-09-29 12:16 UTC, xcelxlorx reviewed
넵 변경사항 확인했습니다 수고하셨습니다!

2023-09-29 12:19 UTC, sososo0 commented
commit 50개 달성...~👍  merge하겠습니다!

2023-09-29 12:19 UTC, merged