프로필, 유저 기록, 참여 기록, 신청 여부 API 구현
Step3-kakao-tech-campus/Team3_BE pull request #41
Opened 2023-10-07 18:28 UTC by xcelxlorx

## Summary

- 신청: 신청 상태 조회
- 프로필: 사용자 목록 조회
- 프로필: 사용자 상세 조회
- 프로필: 자신의 프로필 조회
- 프로필: 자신의 프로필 수정
- 기록: 유저 기록 조회
- 기록: 참여 기록 조회

위의 api를 구현했습니다.

## Description

### 유저 기록 조회
- countGames()로 게임 수를 가져옵니다. applicant_tb에는 모집글 작성자가 들어가 있지 않기 때문에 모집글 작성자일 경우를 추가로 가져왔습니다.
- average는 (int)로 변환하기 때문에 내림해서 반환합니다. 

### 참여 기록 조회
조건 파라미터가 많다 보니 보내야 하는 쿼리 종류가 대략 32개라서 동적 쿼리를 사용했습니다. jpa specification로 구현했고 실무에서는 잘 사용하지 않는다고 합니다.
- loadPosts()로 post list를 가져옵니다. 
- conditionEqual()로 condition 조건을 확인합니다.
- statusEqual()로 status 조건을 확인합니다.
- cityIdEqual()로 cityId 조건을 확인합니다. 
- postIdLessThan()로 key 조건을 확인합니다. 
- createdAtBetween()으로 start <= post.startTime <= end 조건을 확인합니다. '2023-09' 형태로 데이터를 받아서 appendDay()에서 날짜를 추가해서 LocalDateTime 형태로 변환합니다.  

양방향을 사용하지 않고 자바 코드로 구현하려고 하다보니 <post.id, List<Score>> 형태의 map을 넘겨주게 되었습니다. 
- 참여 기록마다 여러 개의 스코어가 존재하기 때문에 getScoreMap()은 각 post.id와 참여 기록 조회 대상 userId로 score list를 가져와서 <post.id, score list>로 map을 반환합니다. 
- getMemberMap()는 참여 기록마다 신청자 목록의 유저들을 가져옵니다. 현재 applicant_tb에는 모집글 작성자가 들어가 있지 않기 때문에 모집글 작성자를 추가했습니다. 멤버에서 참여 기록 조회 대상 userId는 제외해야 하므로 해당 로직을 추가했습니다. 
- getRateMap()는 참여 기록마다 신청자 목록을 가져와서 applicant id로 userRate에서 평가 목록을 가져옵니다. <post, 각 모집글에 포함된 신청자들이 평가한 리스트>를 map으로 반환합니다. 해당 글의 신청자들이 아무도 평가하지 않았을 경우 리스트는 null이 됩니다. response의 MemberDto에서 평가 리스트 중 평가 대상 id가 현재 member.id와 동일한 아이템이 있다면 true를 반환합니다. 

별점 api는 구현 못했습니다. applicant_id로 별점을 등록할 때 참여 기록에서 멤버를 눌러서 평가를 하게 되면 참여 기록 response에 따로 신청 id를 넘겨주지 않는다면 등록을 못할 것 같은데 프론트에서 어떻게 applicant id를 가져와서 넘겨주나요?? 

하다보니 코드 양이 길어졌습니닷.. 😓 잘못된 로직이 있다면 말씀해주세요.

<details>
<summary>대충 테스트 데이터</summary>
INSERT INTO user_tb (name, email, password, district_id, role)
VALUES ('김볼링', 'test@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('볼링볼링', 'test1@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('박볼', 'test3@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링링', 'test4@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('볼링링', 'test5@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼', 'test6@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링륑', 'test7@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('주주', 'test8@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('son', 'test9@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼2', 'test10@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('볼링링1', 'test11@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('볼스', 'test12@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링2', 'test13@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링3', 'test14@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링4', 'test15@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링5', 'test16@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링6', 'test17@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링7', 'test18@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링8', 'test19@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링9', 'test20@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링10', 'test21@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링11', 'test22@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링12', 'test23@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링13', 'test24@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링14', 'test25@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER'),
       ('김볼링링15', 'test26@test.com', '{bcrypt}$2a$10$yK46P9/7TyA2J4z69uEEhOdInb6a7lgHNWVfqftsQSwvLgwSZv9Mq', 1, 'ROLE_USER');

INSERT INTO post_tb (title, user_id, district_id, start_time, due_time, content, is_close)
VALUES ('불금 볼링 점수 내기 하실 분~', 1, 469, '2023-09-01', '2023-11-29', '볼링 점수 내기합시다.', false),
       ('불금 볼링 점수 내기 하실 분~', 1, 469, '2023-09-01', '2023-11-29', '볼링 점수 내기합시다.', false),
       ('불금 볼링 점수 내기 하실 분~', 1, 469, '2023-09-08', '2023-11-29', '볼링 점수 내기합시다.', false),
       ('불금 볼링 점수 내기 하실 분~', 1, 469, '2023-09-08', '2023-11-29', '볼링 점수 내기합시다.', false),
       ('불금 볼링 점수 내기 하실 분~', 1, 469, '2023-08-05', '2023-11-29', '볼링 점수 내기합시다.', false),
        ('불금 볼링 점수 내기 하실 분~', 2, 3, '2023-09-01', '2023-11-29', '볼링 점수 내기합시다.', false),
        ('불금 볼링 점수 내기 하실 분~', 2, 4, '2023-09-01', '2023-11-29', '볼링 점수 내기합시다.', false),
        ('불금 볼링 점수 내기 하실 분~', 2, 4, '2023-09-01', '2023-11-29', '볼링 점수 내기합시다.', false),
        ('불금 볼링 점수 내기 하실 분~', 2, 4, '2023-08-01', '2023-11-29', '볼링 점수 내기합시다.', false),
        ('불금 볼링 점수 내기 하실 분~', 2, 1, '2023-09-01', '2023-11-29', '볼링 점수 내기합시다.', false),
        ('불금 볼링 점수 내기 하실 분~', 3, 1, '2023-10-01', '2023-11-29', '볼링 점수 내기합시다.', true),
        ('불금 볼링 점수 내기 하실 분~', 3, 1, '2023-08-01', '2023-11-29', '볼링 점수 내기합시다.', true),
        ('불금 볼링 점수 내기 하실 분~', 3, 1, '2023-08-01', '2023-11-29', '볼링 점수 내기합시다.', true),
        ('불금 볼링 점수 내기 하실 분~', 3, 1, '2023-08-01', '2023-11-29', '볼링 점수 내기합시다.', true),
        ('불금 볼링 점수 내기 하실 분~', 3, 1, '2023-08-01', '2023-11-29', '볼링 점수 내기합시다.', true),
       ('불금 볼링 점수 내기 하실 분~', 4, 469, '2023-10-01', '2023-11-29', '볼링 점수 내기합시다.', true),
       ('불금 볼링 점수 내기 하실 분~', 4, 469, '2023-08-01', '2023-11-29', '볼링 점수 내기합시다.', true),
       ('불금 볼링 점수 내기 하실 분~', 4, 469, '2023-08-01', '2023-11-29', '볼링 점수 내기합시다.', true),
       ('불금 볼링 점수 내기 하실 분~', 4, 469, '2023-08-01', '2023-11-29', '볼링 점수 내기합시다.', true),
       ('불금 볼링 점수 내기 하실 분~', 1, 469, '2023-08-01', '2023-11-29', '볼링 점수 내기합시다.', true);

INSERT INTO comment_tb (post_id, user_id, parent_id, content)
VALUES (1, 2, null, '저 해도 되나요?'),
       (1, 1, 1, '신청해주세요~');

INSERT INTO applicant_tb (user_id, post_id, status)
VALUES (1, 6, true),
       (1, 7, false),
       (1, 8, false),
       (1, 9, false),
       (1, 10, false),
       (1, 11, false),
       (1, 12, false),
       (1, 13, false),
       (1, 14, false),
       (1, 15, false),
       (1, 16, true),
       (1, 17, true),
       (1, 18, true),
       (1, 19, true),
       (2, 1, true),
       (3, 2, true),
       (4, 1, true),
       (5, 1, true),
       (11, 6, true),
       (7, 6, true),
       (8, 6, true),
       (9, 6, true),
       (10, 6, true);

INSERT INTO score_tb (user_id, post_id, score)
VALUES
    (1, 6, 100),
    (1, 1, 150),
    (1, 6, 45);

INSERT INTO user_rate_tb(applicant_id, user_id, star_count)
VALUES (1, 11, 5),
       (1, 7, 5),
       (1, 8, 5),
       (1, 9, 5),
       (1, 10, 5),
       (20, 10, 5),
       (20, 11, 5),
       (20, 8, 5),
       (20, 9, 5);
</details>

## Related Issue

Issue Number: #27
Issue Number: close #36

2023-10-08 11:16 UTC, yunzae commented
별점api관련해서는 회의시간 때 이야기 해보면 좋을 것 같습니다.

2023-10-08 14:22 UTC, sososo0 commented
5주차에는 포함시키지 않고 6주차로 넘기겠습니다~

2023-10-11 02:59 UTC, xcelxlorx commented
conflict 해결 후 수정 사항 반영했습니다. 확인 부탁드립니다!

2023-10-11 20:06 UTC, jagaldol requested changes
리뷰가 좀 늦었네요.

전부 다 읽고 나서 보니까 조금 꼬인 게 유저 평가할 때는 자신의 신청 id를 path variable로 넣고 상대방 id를 추가로 받아서 평가를 남겨야 합니다. 따라서 참여기록 조회 api에서 members에 참여 같이한 사람들에 대해 그 사람들의 신청id를 주는 것이 아닌 post에 대한 지신의 신청 id 하나만 주면 됩니다.

혹시 평가했는지 안했는지 판단하는 부분이나 그 외 userRate를 사용하는 부분에서 자신의 신청 id가 아닌 상대의 신청id라고 생각하고 만들어 꼬인부분 없는지 확인 부탁드립니다.

별점 등록의 경우 body에 rating에 추가로 userId 하나 더 받으면 될 거 같습니다.

2023-10-11 20:12 UTC, jagaldol commented
쿼리 테스트 도중 참여기록 조회 api에서 주소 정보가 추가 쿼리 발생하는 걸 확인했습니다.
찾아보다가 해결법 바로 찾아서 주소 정보를 join fetch 하도록 브랜치 위에 커밋 하나 추가하였습니다.

2023-10-12 08:34 UTC, xcelxlorx commented on src/main/java/com/bungaebowling/server/user/User.java
> +    private LocalDateTime updatedAt;
수정한 시간이 저장되야 할 것 같아서 추가했는데 빼도 될 것 같습니다!

2023-10-12 14:31 UTC, xcelxlorx commented
수정 완료했습니다. 확인 부탁드립니다!

2023-10-12 19:33 UTC, jagaldol approved these changes
수고 많으셨습니다.
확인 완료하였고 테스트 과정에서 data.sql에 김볼링의 자신이 쓴 글에 대한 신청도  추가하여 정상 동작하도록 수정했습니다. 그러면서 모집글 생성(저장)의 메서드 명이 명확하지 않은 점을 발견해 이 부분을 가볍게 refactoring 해서 커밋 하나 쌓았습니다. 따로 로직은 건드린게 없습니다.

approve 할테니 마지막 점검하시고 이상 없으시면 merge하여 서버 배포 해주셔도 되겠습니다!

2023-10-12 23:17 UTC, merged